import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import {AuthContextProvider} from "@/context/AuthContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body
          className={`${inter.className} bg-black text-white overflow-hidden w-screen h-screen`}
        >
        <NavBar />
        {children}
        </body>
      </AuthContextProvider>
    </html>
  )
}
